[package]
name = "blockstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.4.2", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.40.0", features = ["full"] }
